# Utiliser l'image Azure Functions avec support pour SSH et débogage
FROM mcr.microsoft.com/azure-functions/python:4-python3.10-appservice

# Définir le répertoire de travail
WORKDIR /home/site/wwwroot

# Copier le fichier requirements.txt pour gérer les dépendances
COPY requirements.txt .

# Installer les dépendances Python à partir du fichier requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Installer TheHarvester
RUN apt-get update && apt-get install -y \
    git dnsutils \
    && git clone https://github.com/laramies/theHarvester.git /opt/theHarvester \
    && pip install --no-cache-dir -r /opt/theHarvester/requirements.txt

# Installer Sherlock
RUN pip install --no-cache-dir sherlock-project

# Copier le code de l'application et les tests dans le conteneur
COPY . .

# Commande par défaut pour exécuter les tests
CMD ["python3", "-m", "unittest", "discover", "-s", "test", "-p", "test_*.py", "-v"]

